In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([-0.94464734,  0.68234182,  0.86803667,  1.4630713 ,  0.31710879,
       -1.90026727,  0.18530587, -0.64567925, -0.06990585,  1.7421925 ])

In [6]:
B = np.random.randn(10)

In [7]:
B

array([ 0.63300581,  0.46710481,  0.57310639,  0.37190238, -1.0310185 ,
        0.77455202,  0.54898678,  0.93995481,  0.5987991 , -0.44188455])

In [8]:
# Binary Functions

In [9]:
np.add(A,B)

array([-0.31164152,  1.14944662,  1.44114306,  1.83497369, -0.7139097 ,
       -1.12571526,  0.73429265,  0.29427556,  0.52889326,  1.30030794])

In [10]:
np.maximum(A,B)

array([0.63300581, 0.68234182, 0.86803667, 1.4630713 , 0.31710879,
       0.77455202, 0.54898678, 0.93995481, 0.5987991 , 1.7421925 ])

In [11]:
np.minimum(A,B)

array([-0.94464734,  0.46710481,  0.57310639,  0.37190238, -1.0310185 ,
       -1.90026727,  0.18530587, -0.64567925, -0.06990585, -0.44188455])

In [12]:
import webbrowser
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
webbrowser.open(website)

True